[package]
name = "norg-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
janetrs = "0.8.0"
serde = { version = "1.0.219", features = ["derive"] }
tree-sitter = "0.25.3"
tree-sitter-norg = { path = "../tree-sitter-norg3" }
